spring:
  #thymeleaf static path setting
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  # setting MySQL connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coupon?serverTimezone=Asia/Seoul
    username: username
    password: password
decorator:
  datasource:
    p6spy:
      enable-logging: false
